// FILE: src/products/moba_signal/data.ts
// ─── Moba Signal — seed dataset for the prototype ────────────────────────────
//
// Deterministic sample data so the dashboard can be evaluated before any agent
// pipeline exists. Everything is computed against `asOf`, never against the
// wall clock. The competitor set and event calendar follow the PRD seed scope;
// the individual items are illustrative, not collected intelligence.
//
// Ownership labels are data, not copy: Diamond renders as "Diamond (part of
// Moba)" and Staalkat as "Staalkat (part of Sanovo)" wherever the name appears.

import type { SignalDataset } from './types'

export const SIGNAL_DEMO: SignalDataset = {
  asOf: '2026-08-19',

  // ── Entities ────────────────────────────────────────────────────────────────
  entities: [
    { id: 'moba',      name: 'Moba',        type: 'brand',      ownership: { kind: 'moba' }, addedOn: '2026-08-01', regions: ['global'] },
    { id: 'diamond',   name: 'Diamond',     type: 'brand',      ownership: { kind: 'moba' }, addedOn: '2026-08-01', regions: ['americas'],
      note: 'Installed base and trade-press presence in North America. Tracked so Americas mentions classify correctly, never as competitor presence.' },
    { id: 'sanovo',    name: 'Sanovo',      type: 'competitor', ownership: { kind: 'independent' }, priority: true,  addedOn: '2026-08-01', regions: ['global'], backfilledTo: '2024-08-01' },
    { id: 'staalkat',  name: 'Staalkat',    type: 'brand',      ownership: { kind: 'group', parentId: 'sanovo', parentName: 'Sanovo' }, addedOn: '2026-08-01', regions: ['europe'] },
    { id: 'vencomatic',name: 'Vencomatic Group', type: 'competitor', ownership: { kind: 'independent' }, addedOn: '2026-08-01', regions: ['europe'] },
    { id: 'prinzen',   name: 'Prinzen',     type: 'competitor', ownership: { kind: 'group', parentId: 'vencomatic', parentName: 'Vencomatic' }, priority: true, addedOn: '2026-08-01', regions: ['europe', 'asia'], backfilledTo: '2025-02-01' },
    { id: 'nabel',     name: 'NABEL',       type: 'competitor', ownership: { kind: 'independent' }, priority: true,  addedOn: '2026-08-01', regions: ['asia'], backfilledTo: '2025-06-01' },
    { id: 'kyowa',     name: 'Kyowa',       type: 'competitor', ownership: { kind: 'independent' }, addedOn: '2026-08-01', regions: ['asia'] },
    { id: 'zenyer',    name: 'Zenyer',      type: 'competitor', ownership: { kind: 'independent' }, priority: true,  addedOn: '2026-08-01', regions: ['asia', 'mea'], backfilledTo: '2025-01-01' },
    { id: 'riva',      name: 'Riva Selegg', type: 'competitor', ownership: { kind: 'independent' }, addedOn: '2026-08-01', regions: ['europe'] },
    // Markets and customers referenced by signals
    { id: 'mkt-vietnam', name: 'Vietnam',        type: 'market',   ownership: { kind: 'independent' }, addedOn: '2026-08-01', regions: ['asia'] },
    { id: 'mkt-sea',     name: 'Southeast Asia', type: 'market',   ownership: { kind: 'independent' }, addedOn: '2026-08-01', regions: ['asia'] },
    { id: 'mkt-brazil',  name: 'Brazil',         type: 'market',   ownership: { kind: 'independent' }, addedOn: '2026-08-01', regions: ['americas'] },
    { id: 'cust-bahuan', name: 'Ba Huan JSC',    type: 'customer', ownership: { kind: 'independent' }, addedOn: '2026-08-01', regions: ['asia'],
      note: 'Major Vietnamese egg producer. On the Moba strategic account list.' },
  ],

  // ── Signals: 24 months, competitor and Moba lanes ──────────────────────────
  signals: [
    // 2024 H2 (backfilled)
    {
      id: 's-01', date: '2024-09-12', entityId: 'sanovo', linkedEntityIds: ['mkt-sea'],
      title: 'Sanovo opens regional service hub in Bangkok',
      summary: 'New service and spare-parts hub covering Southeast Asia. Framed around response time for processing customers.',
      type: 'facility', region: 'asia', category: 'service',
      proximity: 2, materiality: 3, credibility: 3, status: 'verified',
      sourceId: 'src-sanovo', sourceUrl: 'https://www.sanovogroup.com/news/bangkok-hub',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-02', date: '2024-11-06', entityId: 'moba', linkedEntityIds: [],
      title: 'Moba at EuroTier 2024, Hannover',
      summary: 'Stand presence with grading portfolio. iMoba dashboard demo.',
      type: 'moba', region: 'europe', category: 'corporate',
      proximity: 3, materiality: 1, credibility: 3, status: 'verified',
      sourceId: 'src-moba-events', sourceUrl: 'https://www.moba.net/events',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-03', date: '2024-11-20', entityId: 'nabel', linkedEntityIds: [],
      title: 'NABEL launches compact grader for mid-capacity plants',
      summary: 'New machine aimed at 60k eggs per hour plants, positioned on footprint and energy use.',
      type: 'launch', region: 'asia', category: 'grading',
      proximity: 2, materiality: 2, credibility: 2, status: 'verified',
      sourceId: 'src-wattpoultry', sourceUrl: 'https://www.wattagnet.com/nabel-compact-grader',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-04', date: '2025-01-15', entityId: 'zenyer', linkedEntityIds: ['mkt-sea'],
      title: 'Zenyer wins grading line at Philippine layer operation',
      summary: 'First publicly announced Zenyer install in the Philippines. 90k eggs per hour.',
      type: 'win', region: 'asia', category: 'grading',
      proximity: 2, materiality: 2, credibility: 2, status: 'verified',
      sourceId: 'src-poultryworld', sourceUrl: 'https://www.poultryworld.net/zenyer-philippines',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-05', date: '2025-03-12', entityId: 'moba', linkedEntityIds: ['mkt-sea'],
      title: 'Moba at VIV Asia 2025, Bangkok',
      summary: 'Full line demo. Launch moment for the updated Forta grader in the region.',
      type: 'moba', region: 'asia', category: 'grading',
      proximity: 3, materiality: 2, credibility: 3, status: 'verified',
      sourceId: 'src-moba-events', sourceUrl: 'https://www.moba.net/events',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-06', date: '2025-03-13', entityId: 'sanovo', linkedEntityIds: ['mkt-sea'],
      title: 'Sanovo shows integrated processing line at VIV Asia 2025',
      summary: 'Breaking, separating and pasteurising presented as one line with a single control layer. Stand grew versus 2023 edition.',
      type: 'launch', region: 'asia', category: 'processing',
      proximity: 3, materiality: 3, credibility: 3, status: 'verified',
      sourceId: 'src-viv', sourceUrl: 'https://www.vivasia.nl/exhibitor/sanovo',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-10', assertedBy: 'curator', humanReviewed: true,
      claimIds: ['c-processing'],
      annotations: [{
        id: 'a-01', author: 'Chief Analyst', role: 'Analyst', createdAt: '2026-08-10T09:00:00Z',
        means: 'Sanovo is selling the line as one integrated story, which is the same ground our keten-verhaal claims.',
        consider: 'Sharpen the integration proof points before IPPE. Their control layer is new; ours is installed at scale.',
        whoNeedsToKnow: 'Product marketing, processing PM',
        promotedToBriefing: true, replies: [],
      }],
    },
    {
      id: 's-07', date: '2025-05-08', entityId: 'staalkat', linkedEntityIds: ['mkt-brazil'],
      title: 'Staalkat grader installed at Brazilian packer',
      summary: 'Trade press covers a Staalkat 130k install near Sao Paulo. Counts toward Sanovo group.',
      type: 'win', region: 'americas', category: 'grading',
      proximity: 2, materiality: 2, credibility: 2, status: 'verified',
      sourceId: 'src-wattpoultry', sourceUrl: 'https://www.wattagnet.com/staalkat-brazil',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-08', date: '2025-06-24', entityId: 'prinzen', linkedEntityIds: [],
      title: 'Prinzen introduces robotic tray stacking cell',
      summary: 'Labour-reduction positioning. Shown first at a Vencomatic open house.',
      type: 'launch', region: 'europe', category: 'grading',
      proximity: 2, materiality: 2, credibility: 3, status: 'verified',
      sourceId: 'src-prinzen', sourceUrl: 'https://www.prinzen.com/news/robotic-stacking',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-09', date: '2025-09-17', entityId: 'moba', linkedEntityIds: [],
      title: 'Moba publishes iMoba 3 with fleet benchmarking',
      summary: 'Connected-services release. Public claim: grading data across sites in one view.',
      type: 'moba', region: 'global', category: 'digital',
      proximity: 3, materiality: 2, credibility: 3, status: 'verified',
      sourceId: 'src-moba-events', sourceUrl: 'https://www.moba.net/news/imoba-3',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      claimIds: ['c-data'],
      annotations: [],
    },
    {
      id: 's-10', date: '2025-10-02', entityId: 'zenyer', linkedEntityIds: [],
      title: 'Zenyer files patent family on optical crack detection',
      summary: 'Three related filings on camera-based crack and dirt detection at speed.',
      type: 'launch', region: 'asia', category: 'detection',
      proximity: 2, materiality: 2, credibility: 3, status: 'verified',
      sourceId: 'src-patents', sourceUrl: 'https://worldwide.espacenet.com/zenyer-crack-detection',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      claimIds: ['c-detection'],
      annotations: [],
    },
    {
      id: 's-11', date: '2025-11-19', entityId: 'sanovo', linkedEntityIds: [],
      title: 'Sanovo hires former dairy-tech executive as CCO',
      summary: 'New chief commercial officer with processing-industry background.',
      type: 'personnel', region: 'europe', category: 'corporate',
      proximity: 2, materiality: 2, credibility: 3, status: 'verified',
      sourceId: 'src-linkedin', sourceUrl: 'https://www.linkedin.com/company/sanovo',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-12', date: '2026-01-27', entityId: 'moba', linkedEntityIds: [],
      title: 'Moba at IPPE 2026, Atlanta',
      summary: 'US presence under the Moba name. Diamond installed base a recurring conversation on the stand.',
      type: 'moba', region: 'americas', category: 'corporate',
      proximity: 3, materiality: 1, credibility: 3, status: 'verified',
      sourceId: 'src-moba-events', sourceUrl: 'https://www.ippexpo.org/exhibitors',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-13', date: '2026-01-28', entityId: 'zenyer', linkedEntityIds: [],
      title: 'Zenyer exhibits in the US for the first time at IPPE 2026',
      summary: 'Small stand, grading only. First observed move outside Asia and MEA.',
      type: 'launch', region: 'americas', category: 'grading',
      proximity: 2, materiality: 3, credibility: 3, status: 'verified',
      sourceId: 'src-viv', sourceUrl: 'https://www.ippexpo.org/exhibitors/zenyer',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      disposition: 'watch', recommendedAction: 'monitor',
      annotations: [{
        id: 'a-02', author: 'Mark de Kock', role: 'Product marketing', createdAt: '2026-08-11T14:00:00Z',
        means: 'Zenyer stepping outside its home region changes the Americas picture, even at small scale.',
        consider: 'Watch their IPPE 2027 stand size. A second, larger appearance would confirm intent.',
        whoNeedsToKnow: 'Americas sales lead',
        promotedToBriefing: false,
        replies: [{
          id: 'r-01', author: 'PM Grading', role: 'Innovation', createdAt: '2026-08-12T08:30:00Z',
          body: 'Their US entry price will matter more than the stand. Any signal on a US service partner yet?',
        }],
      }],
    },
    {
      id: 's-14', date: '2026-02-19', entityId: 'nabel', linkedEntityIds: [],
      title: 'NABEL announces partnership with Japanese robotics firm',
      summary: 'Joint development on end-of-line palletising for egg products.',
      type: 'partnership', region: 'asia', category: 'grading',
      proximity: 2, materiality: 3, credibility: 2, status: 'verified',
      sourceId: 'src-poultryworld', sourceUrl: 'https://www.poultryworld.net/nabel-robotics',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-15', date: '2026-03-10', entityId: 'riva', linkedEntityIds: [],
      title: 'Riva Selegg updates farm packer range',
      summary: 'Incremental refresh, energy use and changeover time as headline specs.',
      type: 'launch', region: 'europe', category: 'grading',
      proximity: 1, materiality: 1, credibility: 2, status: 'verified',
      sourceId: 'src-poultryworld', sourceUrl: 'https://www.poultryworld.net/riva-selegg-range',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-16', date: '2026-04-03', entityId: 'sanovo', linkedEntityIds: ['mkt-vietnam', 'mkt-sea', 'cust-bahuan'],
      title: 'Sanovo announces processing line order from Ba Huan, Vietnam',
      summary: 'Press release names Ba Huan JSC. Breaking and pasteurising line, delivery "later this year". Ba Huan is on the Moba strategic account list.',
      type: 'win', region: 'asia', category: 'processing',
      proximity: 3, materiality: 3, credibility: 2, status: 'verified',
      sourceId: 'src-sanovo', sourceUrl: 'https://www.sanovogroup.com/news/ba-huan-order',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-15', assertedBy: 'collector', humanReviewed: true,
      claimIds: ['c-processing', 'c-partner'],
      touchesMobaAccount: 'Ba Huan JSC',
      disposition: 'threat', recommendedAction: 'respond',
      annotations: [{
        id: 'a-03', author: 'Chief Analyst', role: 'Analyst', createdAt: '2026-08-06T10:00:00Z',
        means: 'A named win at a strategic account, in the segment where we are weakest. Third Sanovo processing win in SEA this quarter.',
        consider: 'Account team should verify scope with the customer relationship. Positioning: do not lead with processing in Vietnam material until this is understood.',
        whoNeedsToKnow: 'CMO, Vietnam account team, processing PM',
        promotedToBriefing: true, replies: [],
      }],
    },
    {
      id: 's-17', date: '2026-04-21', entityId: 'kyowa', linkedEntityIds: [],
      title: 'Kyowa shows washing line upgrade at regional open day',
      summary: 'Modest update, mainly water-use reduction.',
      type: 'launch', region: 'asia', category: 'sustainability',
      proximity: 1, materiality: 1, credibility: 2, status: 'verified',
      sourceId: 'src-poultryworld', sourceUrl: 'https://www.poultryworld.net/kyowa-washing',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-18', date: '2026-05-12', entityId: 'sanovo', linkedEntityIds: ['mkt-sea'],
      title: 'Sanovo processing win at Malaysian egg products plant',
      summary: 'Second SEA processing announcement this quarter. Framed as "full-line partnership".',
      type: 'win', region: 'asia', category: 'processing',
      proximity: 2, materiality: 3, credibility: 2, status: 'verified',
      sourceId: 'src-sanovo', sourceUrl: 'https://www.sanovogroup.com/news/malaysia-plant',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      claimIds: ['c-processing'],
      annotations: [],
    },
    {
      id: 's-19', date: '2026-05-28', entityId: 'prinzen', linkedEntityIds: [],
      title: 'Prinzen job postings: three connected-services roles',
      summary: 'Cluster of software and IoT vacancies referencing "machine data platform". Inference: connected-services push underway.',
      type: 'personnel', region: 'europe', category: 'digital',
      proximity: 2, materiality: 2, credibility: 1, status: 'unverified',
      sourceId: 'src-jobs', sourceUrl: 'https://www.vencomaticgroup.com/careers',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-14', assertedBy: 'analyst', humanReviewed: true,
      inference: true, claimIds: ['c-data'],
      annotations: [],
    },
    {
      id: 's-20', date: '2026-06-09', entityId: 'zenyer', linkedEntityIds: [],
      title: 'Rumour: Zenyer in talks to acquire European distributor',
      summary: 'Single social post from an industry consultant. No corroboration in trade press after ten weeks.',
      type: 'funding', region: 'europe', category: 'corporate',
      proximity: 2, materiality: 3, credibility: 1, status: 'disputed',
      sourceId: 'src-linkedin', sourceUrl: 'https://www.linkedin.com/posts/industry-consultant',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'collector', humanReviewed: true,
      annotations: [{
        id: 'a-04', author: 'Chief Analyst', role: 'Analyst', createdAt: '2026-08-07T11:00:00Z',
        means: 'If true this changes Zenyer EU service reach overnight. Credibility 1, so it stays amber by rule.',
        consider: 'Watch Zenyer and the usual EU distributors for register changes. Do not repeat this externally.',
        whoNeedsToKnow: 'Europe sales lead',
        promotedToBriefing: false, replies: [],
      }],
    },
    {
      id: 's-21', date: '2026-06-17', entityId: 'moba', linkedEntityIds: [],
      title: 'Moba campaign: total cost of ownership series live',
      summary: 'Three-part content series on lifetime cost, feeding the 2027 positioning.',
      type: 'moba', region: 'global', category: 'corporate',
      proximity: 3, materiality: 1, credibility: 3, status: 'verified',
      sourceId: 'src-moba-events', sourceUrl: 'https://www.moba.net/news/tco-series',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'curator', humanReviewed: true,
      claimIds: ['c-tco'],
      annotations: [],
    },
    {
      id: 's-22', date: '2026-07-08', entityId: 'nabel', linkedEntityIds: [],
      title: 'NABEL adds AI inspection module to flagship grader',
      summary: 'Camera plus model retrofit, marketed as "human-grade candling". Claims 99.5 percent dirty-egg detection.',
      type: 'launch', region: 'asia', category: 'detection',
      proximity: 3, materiality: 3, credibility: 2, status: 'verified',
      sourceId: 'src-wattpoultry', sourceUrl: 'https://www.wattagnet.com/nabel-ai-inspection',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-16', assertedBy: 'collector', humanReviewed: true,
      claimIds: ['c-detection'],
      disposition: 'threat', recommendedAction: 'investigate',
      annotations: [{
        id: 'a-05', author: 'Chief Analyst', role: 'Analyst', createdAt: '2026-08-08T09:30:00Z',
        means: 'Direct contest of our detection accuracy claim, with a number attached. The 99.5 figure is their lab condition, not field.',
        consider: 'Ask product for our comparable field figure. Adjust the detection claim wording before it goes into 2027 campaign material.',
        whoNeedsToKnow: 'Product marketing, detection PM',
        promotedToBriefing: true, replies: [],
      }],
    },
    {
      id: 's-23', date: '2026-07-22', entityId: 'staalkat', linkedEntityIds: [],
      title: 'Staalkat announces certification for EU packaging directive',
      summary: 'Compliance milestone, marketed to EU packers ahead of 2027 enforcement.',
      type: 'certification', region: 'europe', category: 'sustainability',
      proximity: 2, materiality: 1, credibility: 3, status: 'verified',
      sourceId: 'src-sanovo', sourceUrl: 'https://www.sanovogroup.com/news/staalkat-certification',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'collector', humanReviewed: true,
      claimIds: ['c-sustainability'],
      annotations: [],
    },
    // ── Last 30 days ──
    {
      id: 's-24', date: '2026-07-29', entityId: 'zenyer', linkedEntityIds: ['mkt-sea'],
      title: 'Zenyer wins grading contract at Indonesian integrator',
      summary: 'Announced on the customer side first, confirmed by Zenyer social two days later. 2x 120k lines.',
      type: 'win', region: 'asia', category: 'grading',
      proximity: 2, materiality: 2, credibility: 2, status: 'verified',
      sourceId: 'src-poultryworld', sourceUrl: 'https://www.poultryworld.net/zenyer-indonesia',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-06', assertedBy: 'collector', humanReviewed: true,
      annotations: [],
    },
    {
      id: 's-25', date: '2026-08-04', entityId: 'sanovo', linkedEntityIds: ['mkt-vietnam', 'cust-bahuan'],
      title: 'Trade visit photos suggest Ba Huan line delivery has started',
      summary: 'Customer social post shows Sanovo crates on site. Supports open question on shipment status, not yet conclusive.',
      type: 'win', region: 'asia', category: 'processing',
      proximity: 3, materiality: 2, credibility: 1, status: 'unverified',
      sourceId: 'src-linkedin', sourceUrl: 'https://www.linkedin.com/posts/ba-huan-visit',
      firstSeen: '2026-08-05', lastConfirmed: '2026-08-05', assertedBy: 'verifier', humanReviewed: false,
      inference: true, touchesMobaAccount: 'Ba Huan JSC',
      annotations: [],
    },
    // ── Last 7 days (against a ~2 per week rolling average) ──
    {
      id: 's-26', date: '2026-08-13', entityId: 'sanovo', linkedEntityIds: ['mkt-sea'],
      title: 'Sanovo announces third SEA processing win this quarter, Thailand',
      summary: 'Bangkok-area egg products plant. Press release explicitly references "regional momentum".',
      type: 'win', region: 'asia', category: 'processing',
      proximity: 2, materiality: 3, credibility: 2, status: 'verified',
      sourceId: 'src-sanovo', sourceUrl: 'https://www.sanovogroup.com/news/thailand-win',
      firstSeen: '2026-08-13', lastConfirmed: '2026-08-14', assertedBy: 'collector', humanReviewed: true,
      claimIds: ['c-processing'],
      annotations: [],
    },
    {
      id: 's-27', date: '2026-08-14', entityId: 'prinzen', linkedEntityIds: [],
      title: 'Prinzen teases "connected packer" for SPACE 2026',
      summary: 'Teaser video, no specs. Ties to the earlier job-posting cluster.',
      type: 'launch', region: 'europe', category: 'digital',
      proximity: 2, materiality: 2, credibility: 2, status: 'unverified',
      sourceId: 'src-prinzen', sourceUrl: 'https://www.prinzen.com/news/space-teaser',
      firstSeen: '2026-08-14', lastConfirmed: '2026-08-14', assertedBy: 'collector', humanReviewed: false,
      claimIds: ['c-data'],
      annotations: [],
    },
    {
      id: 's-28', date: '2026-08-17', entityId: 'nabel', linkedEntityIds: [],
      title: 'NABEL session slot confirmed at Saudi Agriculture 2026',
      summary: 'Speaking on "AI in egg quality" in Riyadh. First NABEL appearance at this event.',
      type: 'launch', region: 'mea', category: 'detection',
      proximity: 2, materiality: 1, credibility: 3, status: 'verified',
      sourceId: 'src-viv', sourceUrl: 'https://saudi-agriculture.com/programme',
      firstSeen: '2026-08-17', lastConfirmed: '2026-08-17', assertedBy: 'collector', humanReviewed: false,
      annotations: [],
    },
    {
      id: 's-29', date: '2026-08-18', entityId: 'diamond', linkedEntityIds: [],
      title: 'US trade article references Diamond installed base in Midwest',
      summary: 'Spare-parts and retrofit market piece. Classified under Moba, not competitor presence.',
      type: 'launch', region: 'americas', category: 'service',
      proximity: 3, materiality: 1, credibility: 2, status: 'verified',
      sourceId: 'src-wattpoultry', sourceUrl: 'https://www.wattagnet.com/midwest-retrofit',
      firstSeen: '2026-08-18', lastConfirmed: '2026-08-18', assertedBy: 'collector', humanReviewed: false,
      annotations: [],
    },
    {
      id: 's-30', date: '2026-08-11', entityId: 'sanovo', linkedEntityIds: ['mkt-sea'],
      title: 'Sanovo hiring a Field Service Engineer in Malaysia',
      summary: 'New vacancy on the careers site for a Field Service Engineer based in Petaling Jaya, alongside international field-service and machine-builder roles in the Netherlands. Inference: a service base in Southeast Asia, not a one-off dispatch.',
      type: 'personnel', region: 'asia', category: 'service',
      proximity: 2, materiality: 2, credibility: 2, status: 'unverified',
      sourceId: 'src-sanovo-jobs', sourceUrl: 'https://www.sanovogroup.com/careers',
      firstSeen: '2026-08-27', lastConfirmed: '2026-08-27', assertedBy: 'analyst', humanReviewed: true,
      inference: true,
      disposition: 'watch', recommendedAction: 'investigate',
      annotations: [{
        id: 'a-04', author: 'Mark de Kock', role: 'Product marketing', createdAt: '2026-08-27T09:00:00Z',
        means: 'A locally based service engineer follows an installed base. This lines up with three SEA processing wins this quarter: they are staffing to support what they have sold, which makes the region stickier for them.',
        consider: 'Confirm whether this is a first local hire or a second. Check our own SEA service coverage against the same map before the next regional review.',
        whoNeedsToKnow: 'Asia Pacific service lead, processing PM',
        promotedToBriefing: false, replies: [],
      }],
    },
  ],

  // ── Claims tracker ──────────────────────────────────────────────────────────
  claims: [
    {
      id: 'c-grading', pillar: 'Product leadership',
      claim: 'Highest grading accuracy at every capacity tier',
      status: 'adjacent', trend: 0,
      competitorClaims: [
        { entityId: 'nabel', wording: '選別精度で業界をリードする', sourceLanguage: 'Japanese', translation: 'Industry-leading grading precision', sourceUrl: 'https://www.nabel.co.jp', lastSeen: '2026-07-08' },
      ],
    },
    {
      id: 'c-processing', pillar: 'Full line',
      claim: 'One partner from grading into processing',
      status: 'contested', trend: -1,
      competitorClaims: [
        { entityId: 'sanovo', wording: 'The only true full-line partner in egg processing', sourceUrl: 'https://www.sanovogroup.com', lastSeen: '2026-08-13' },
      ],
    },
    {
      id: 'c-detection', pillar: 'Product leadership',
      claim: 'Best-in-class crack and dirt detection',
      status: 'contested', trend: -1,
      competitorClaims: [
        { entityId: 'nabel', wording: 'Human-grade candling, 99.5% dirty-egg detection', sourceUrl: 'https://www.wattagnet.com/nabel-ai-inspection', lastSeen: '2026-07-08' },
        { entityId: 'zenyer', wording: '智能检测，无损分级', sourceLanguage: 'Chinese', translation: 'Intelligent detection, damage-free grading', sourceUrl: 'https://www.zenyer.com', lastSeen: '2026-06-01' },
      ],
    },
    {
      id: 'c-data', pillar: 'Digital',
      claim: 'The only grading data platform proven across sites (iMoba)',
      status: 'adjacent', trend: 0,
      competitorClaims: [
        { entityId: 'prinzen', wording: 'Connected packer, machine data platform (teaser)', sourceUrl: 'https://www.prinzen.com/news/space-teaser', lastSeen: '2026-08-14' },
      ],
    },
    {
      id: 'c-partner', pillar: 'Business partner',
      claim: 'We maximise return per egg, not machine throughput',
      status: 'uncontested', trend: 1,
      competitorClaims: [],
    },
    {
      id: 'c-tco', pillar: 'Business partner',
      claim: 'Lowest total cost of ownership over the machine lifetime',
      status: 'uncontested', trend: 0,
      competitorClaims: [],
    },
    {
      id: 'c-service', pillar: 'Service',
      claim: 'The largest global service network in the industry',
      status: 'adjacent', trend: 0,
      competitorClaims: [
        { entityId: 'sanovo', wording: 'Local service, global backing: hubs on every continent', sourceUrl: 'https://www.sanovogroup.com/service', lastSeen: '2026-05-01' },
      ],
    },
    {
      id: 'c-sustainability', pillar: 'Sustainability',
      claim: 'Lowest energy use per graded egg',
      status: 'conceded', trend: -1,
      competitorClaims: [
        { entityId: 'riva', wording: 'Classe energetica leader del settore', sourceLanguage: 'Italian', translation: 'Industry-leading energy class', sourceUrl: 'https://www.rivaselegg.com', lastSeen: '2026-03-10' },
        { entityId: 'kyowa', wording: 'Water and energy reduction across the washing line', sourceUrl: 'https://www.poultryworld.net/kyowa-washing', lastSeen: '2026-04-21' },
      ],
    },
  ],

  whitespace: [
    { id: 'w-01', territory: 'Labour reduction as a quantified claim', rationale: 'Prinzen positions robotics, but nobody claims a number (operators per line, per shift). First mover owns the metric.' },
    { id: 'w-02', territory: 'Food-safety traceability from farm to carton', rationale: 'Fragmented claims exist per machine. No competitor claims the chain.' },
  ],

  // ── Head to head ────────────────────────────────────────────────────────────
  axes: [
    { key: 'capacity',       label: 'Grading capacity tiers' },
    { key: 'processing',     label: 'Processing' },
    { key: 'detection',      label: 'Detection & vision' },
    { key: 'digital',        label: 'Digital & connected services' },
    { key: 'service',        label: 'Service network reach' },
    { key: 'sustainability', label: 'Sustainability claims' },
    { key: 'labour',         label: 'Labour automation', proposed: true,
      proposedRationale: 'Positioning agent: three competitors made labour-reduction claims in the last two quarters. The current axes cannot hold them.' },
  ],
  headToHead: [
    {
      entityId: 'sanovo',
      summary: 'Closest full-line rival. Strongest where we are weakest: processing. Group includes Staalkat for grading.',
      cells: [
        { axis: 'capacity',       moba: 'Full range to 250k eggs/hr',            competitor: 'Staalkat range to 180k eggs/hr',            edge: 1, confidence: 3, lastVerified: '2026-08-10' },
        { axis: 'processing',     moba: 'Partner-dependent beyond breaking',      competitor: 'Full line: breaking, separating, pasteurising, drying', edge: -1, confidence: 3, lastVerified: '2026-08-13' },
        { axis: 'detection',      moba: 'Integrated crack/dirt/leak detection',   competitor: 'Comparable on paper, fewer field references', edge: 1, confidence: 2, lastVerified: '2026-07-15' },
        { axis: 'digital',        moba: 'iMoba 3, multi-site benchmarking',       competitor: 'Single control layer per line, no cross-site platform seen', edge: 1, confidence: 2, lastVerified: '2026-08-10' },
        { axis: 'service',        moba: 'Global network, strongest in EU/US',     competitor: 'Growing: Bangkok hub 2024, hub claims on every continent', edge: 0, confidence: 3, lastVerified: '2026-08-10' },
        { axis: 'sustainability', moba: 'Energy per egg published for top range', competitor: 'EU packaging certification (Staalkat), no energy figure', edge: 0, confidence: 2, lastVerified: '2026-07-22' },
      ],
    },
    {
      entityId: 'nabel',
      summary: 'Technology-led challenger from Japan. Detection is the contested front.',
      cells: [
        { axis: 'capacity',       moba: 'Full range to 250k eggs/hr',            competitor: 'Mid-range focus, compact grader for 60k plants', edge: 1, confidence: 3, lastVerified: '2026-08-05' },
        { axis: 'processing',     moba: 'Partner-dependent beyond breaking',      competitor: 'Not present',                                edge: 1, confidence: 3, lastVerified: '2026-08-05' },
        { axis: 'detection',      moba: 'Integrated crack/dirt/leak detection',   competitor: 'New AI inspection module, 99.5% lab claim',   edge: 0, confidence: 2, lastVerified: '2026-08-16' },
        { axis: 'digital',        moba: 'iMoba 3, multi-site benchmarking',       competitor: 'Machine-level dashboards only',               edge: 1, confidence: 2, lastVerified: '2026-06-01' },
        { axis: 'service',        moba: 'Global network, strongest in EU/US',     competitor: 'Japan and East Asia, distributor-led elsewhere', edge: 1, confidence: 3, lastVerified: '2026-06-01' },
        { axis: 'sustainability', moba: 'Energy per egg published for top range', competitor: 'Energy use in compact-grader messaging',       edge: 0, confidence: 2, lastVerified: '2026-06-01' },
      ],
    },
    {
      entityId: 'zenyer',
      summary: 'Price-led expansion out of China. Now visible in SEA wins and a first US appearance.',
      cells: [
        { axis: 'capacity',       moba: 'Full range to 250k eggs/hr',            competitor: 'Range to 120k, aggressive on price',          edge: 1, confidence: 2, lastVerified: '2026-08-06' },
        { axis: 'processing',     moba: 'Partner-dependent beyond breaking',      competitor: 'Basic breaking equipment only',               edge: 1, confidence: 2, lastVerified: '2026-06-01' },
        { axis: 'detection',      moba: 'Integrated crack/dirt/leak detection',   competitor: 'Patent activity on optical crack detection',  edge: 1, confidence: 3, lastVerified: '2026-08-05' },
        { axis: 'digital',        moba: 'iMoba 3, multi-site benchmarking',       competitor: 'Unknown',                                     edge: 1, confidence: 1, lastVerified: '2026-05-01' },
        { axis: 'service',        moba: 'Global network, strongest in EU/US',     competitor: 'China dense, SEA growing, EU rumour unconfirmed', edge: 0, confidence: 2, lastVerified: '2026-08-05' },
        { axis: 'sustainability', moba: 'Energy per egg published for top range', competitor: 'No claims observed',                          edge: 1, confidence: 2, lastVerified: '2026-05-01' },
      ],
    },
    {
      entityId: 'prinzen',
      summary: 'Farm-side specialist inside Vencomatic. Watching the connected-packer teaser.',
      cells: [
        { axis: 'capacity',       moba: 'Full range to 250k eggs/hr',            competitor: 'Farm packers and setters, lower tiers',       edge: 1, confidence: 3, lastVerified: '2026-08-05' },
        { axis: 'processing',     moba: 'Partner-dependent beyond breaking',      competitor: 'Not present',                                 edge: 1, confidence: 3, lastVerified: '2026-08-05' },
        { axis: 'detection',      moba: 'Integrated crack/dirt/leak detection',   competitor: 'Basic detection at farm level',               edge: 1, confidence: 2, lastVerified: '2026-06-01' },
        { axis: 'digital',        moba: 'iMoba 3, multi-site benchmarking',       competitor: 'Connected packer teased for SPACE 2026',      edge: 0, confidence: 1, lastVerified: '2026-08-14' },
        { axis: 'service',        moba: 'Global network, strongest in EU/US',     competitor: 'Vencomatic network, EU-centred',              edge: 1, confidence: 3, lastVerified: '2026-06-01' },
        { axis: 'sustainability', moba: 'Energy per egg published for top range', competitor: 'Animal-welfare framing via Vencomatic',       edge: 0, confidence: 2, lastVerified: '2026-06-01' },
      ],
    },
  ],

  // ── Event radar ─────────────────────────────────────────────────────────────
  events: [
    // ── Past editions of the major recurring shows ──────────────────────────
    // The event radar looks forward, but the historical shows are the backdrop
    // the 12/24-month news clusters plot against: a burst of competitor
    // announcements usually trails the show that produced it. In live mode
    // these come from retaining events after they pass plus a calendar backfill.
    {
      id: 'e-eurotier-24', name: 'EuroTier 2024', location: 'Hannover', country: 'Germany', region: 'europe',
      startDate: '2024-11-12', endDate: '2024-11-15', mobaExhibiting: true,
      competitors: [
        { entityId: 'sanovo', standSqm: 320, standSqmLastEdition: 260 },
        { entityId: 'prinzen' },
        { entityId: 'nabel' },
      ],
      exhibitorListStatus: 'published',
      notes: 'Biennial. Moba showed the grading portfolio and the iMoba demo; Sanovo grew its stand versus 2022.',
    },
    {
      id: 'e-ippe-25', name: 'IPPE 2025', location: 'Atlanta', country: 'United States', region: 'americas',
      startDate: '2025-01-28', endDate: '2025-01-30', mobaExhibiting: true,
      competitors: [{ entityId: 'sanovo' }],
      exhibitorListStatus: 'published',
      notes: 'Diamond carried the Moba presence in North America.',
    },
    {
      id: 'e-vivasia-25', name: 'VIV Asia 2025', location: 'Bangkok', country: 'Thailand', region: 'asia',
      startDate: '2025-03-12', endDate: '2025-03-14', mobaExhibiting: true,
      competitors: [
        { entityId: 'sanovo', standSqm: 180, standSqmLastEdition: 140 },
        { entityId: 'zenyer' },
        { entityId: 'nabel' },
      ],
      exhibitorListStatus: 'published',
      notes: 'Sanovo presented breaking-separating-pasteurising as one line; stand grew versus 2023. Drove the March processing coverage.',
    },
    {
      id: 'e-space-25', name: 'SPACE 2025', location: 'Rennes', country: 'France', region: 'europe',
      startDate: '2025-09-16', endDate: '2025-09-18', mobaExhibiting: true,
      competitors: [{ entityId: 'prinzen' }, { entityId: 'riva' }],
      exhibitorListStatus: 'published',
    },
    {
      id: 'e-ippe-26', name: 'IPPE 2026', location: 'Atlanta', country: 'United States', region: 'americas',
      startDate: '2026-01-27', endDate: '2026-01-29', mobaExhibiting: true,
      competitors: [{ entityId: 'sanovo' }],
      exhibitorListStatus: 'published',
    },
    // Researched from the trade calendar to complete the past 12 months. Dates
    // verified via the organisers and trade press; exhibitor mapping still to do,
    // so competitor and Moba presence are left unasserted (status not-published).
    {
      id: 'e-saudi-25', name: 'Saudi Agriculture 2025', location: 'Riyadh', country: 'Saudi Arabia', region: 'mea',
      startDate: '2025-10-20', endDate: '2025-10-23', mobaExhibiting: true,
      competitors: [],
      exhibitorListStatus: 'partial',
      notes: 'Moba exhibited (grading systems, egg packing). 42nd edition, ~370 exhibitors. Moba presence verified (moba.net); no tracked competitor confirmed.',
    },
    {
      id: 'e-vivmea-25', name: 'VIV MEA 2025', location: 'Abu Dhabi', country: 'United Arab Emirates', region: 'mea',
      startDate: '2025-11-25', endDate: '2025-11-27', mobaExhibiting: true,
      competitors: [
        { entityId: 'sanovo', hall: '09.P014' },
        { entityId: 'prinzen' },
      ],
      exhibitorListStatus: 'published',
      notes: 'Moba booth 09.P071; Sanovo 09.P014; Prinzen (Vencomatic) present. 505 exhibitors, 10,830 visitors. Verified via exhibitor listings.',
    },
    {
      id: 'e-poultryindia-25', name: 'Poultry India 2025', location: 'Hyderabad', country: 'India', region: 'asia',
      startDate: '2025-11-26', endDate: '2025-11-28', mobaExhibiting: false,
      competitors: [],
      exhibitorListStatus: 'not-published',
      notes: '17th edition, ~450 exhibitors. India is the #1 growth market to 2035. Dates verified; no tracked competitor confirmed in the exhibitor list yet.',
    },
    {
      id: 'e-viveurope-26', name: 'VIV Europe 2026', location: 'Utrecht', country: 'Netherlands', region: 'europe',
      startDate: '2026-06-02', endDate: '2026-06-04', mobaExhibiting: true,
      competitors: [
        { entityId: 'sanovo' },
        { entityId: 'prinzen' },
      ],
      exhibitorListStatus: 'published',
      notes: 'Moba in Hall 11.A010, launched the Magna vision grader; Sanovo and Prinzen (Vencomatic) exhibiting. 25th edition, ~470 exhibitors. Verified.',
    },
    // ── Upcoming (the event radar's T-90 to T+30 window) ────────────────────
    {
      id: 'e-ildex-ph', name: 'Ildex Philippines', location: 'Pasay City', country: 'Philippines', region: 'asia',
      startDate: '2026-08-26', endDate: '2026-08-27', mobaExhibiting: true,
      competitors: [
        { entityId: 'zenyer', standSqm: 54, standSqmLastEdition: 36 },
        { entityId: 'sanovo' },
      ],
      exhibitorListStatus: 'published',
      notes: 'Zenyer stand grew 50 percent versus last edition. Pre-event brief issued 27 July.',
    },
    {
      id: 'e-fenavi', name: 'Fenavi', location: 'Cali', country: 'Colombia', region: 'americas',
      startDate: '2026-09-01', endDate: '2026-09-03', mobaExhibiting: true,
      competitors: [{ entityId: 'sanovo' }],
      exhibitorListStatus: 'published',
    },
    {
      id: 'e-space', name: 'SPACE 2026', location: 'Rennes', country: 'France', region: 'europe',
      startDate: '2026-09-15', endDate: '2026-09-17', mobaExhibiting: true,
      competitors: [
        { entityId: 'prinzen', sessions: ['Connected packer reveal (teased)'] },
        { entityId: 'riva' },
      ],
      exhibitorListStatus: 'published',
      notes: 'Prinzen expected to reveal the connected packer here. Positioning agent is briefed to capture wording.',
    },
    {
      id: 'e-ipex', name: 'IPEX', location: 'Lahore', country: 'Pakistan', region: 'asia',
      startDate: '2026-10-08', endDate: '2026-10-10', mobaExhibiting: true,
      competitors: [{ entityId: 'zenyer' }],
      exhibitorListStatus: 'partial',
    },
    {
      id: 'e-elmia', name: 'Elmia Agriculture', location: 'Jönköping', country: 'Sweden', region: 'europe',
      startDate: '2026-10-14', endDate: '2026-10-16', mobaExhibiting: true,
      competitors: [],
      exhibitorListStatus: 'not-published',
    },
    {
      id: 'e-dpp', name: 'Dutch Pork and Poultry Expo', location: 'Hardenberg', country: 'Netherlands', region: 'europe',
      startDate: '2026-10-15', endDate: '2026-10-16', mobaExhibiting: true,
      competitors: [{ entityId: 'prinzen' }],
      exhibitorListStatus: 'partial',
      notes: 'Data quality: source page carried 2025 dates on a 2026 listing. Dates verified with the organiser; collector validation rule added.',
    },
    {
      id: 'e-saudi', name: 'Saudi Agriculture', location: 'Riyadh', country: 'Saudi Arabia', region: 'mea',
      startDate: '2026-10-19', endDate: '2026-10-22', mobaExhibiting: true,
      competitors: [
        { entityId: 'nabel', sessions: ['AI in egg quality'] },
        { entityId: 'zenyer' },
      ],
      exhibitorListStatus: 'published',
      notes: 'First NABEL appearance at this event. Session abstract feeds the claims tracker.',
    },
    {
      id: 'e-ovum', name: 'Ovum Guatemala', location: 'Guatemala City', country: 'Guatemala', region: 'americas',
      startDate: '2026-11-11', endDate: '2026-11-13', mobaExhibiting: true,
      competitors: [],
      exhibitorListStatus: 'not-published',
    },
    {
      id: 'e-cile', name: 'China International Layer Expo', location: 'Nanchang', country: 'China', region: 'asia',
      startDate: '2026-11-18', endDate: '2026-11-20', mobaExhibiting: false,
      competitors: [
        { entityId: 'zenyer', standSqm: 120 },
        { entityId: 'kyowa' },
      ],
      exhibitorListStatus: 'published',
      notes: 'Attendance gap: two priority competitors exhibit, Moba does not. Flagged for the events team.',
    },
    {
      id: 'e-ippe27', name: 'IPPE 2027', location: 'Atlanta', country: 'United States', region: 'americas',
      startDate: '2027-01-26', endDate: '2027-01-28', mobaExhibiting: true,
      competitors: [
        { entityId: 'sanovo', standSqm: 210, standSqmLastEdition: 160 },
        { entityId: 'zenyer' },
      ],
      exhibitorListStatus: 'partial',
      notes: 'Sanovo booked 31 percent more floor than IPPE 2026. Watch Zenyer stand size against their first US appearance.',
    },
    {
      id: 'e-viv27', name: 'VIV Asia 2027', location: 'Bangkok', country: 'Thailand', region: 'asia',
      startDate: '2027-03-10', endDate: '2027-03-12', mobaExhibiting: true,
      competitors: [
        { entityId: 'sanovo' },
        { entityId: 'nabel' },
        { entityId: 'zenyer' },
        { entityId: 'prinzen' },
      ],
      exhibitorListStatus: 'partial',
    },
  ],

  // ── Sources ─────────────────────────────────────────────────────────────────
  sources: [
    { id: 'src-sanovo',       name: 'Sanovo newsroom',                 url: 'https://www.sanovogroup.com/news',     sourceClass: 'competitor-site', status: 'ok',     lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-08-13', itemsLast30d: 6,  scoredItemsLast90d: 9 },
    { id: 'src-prinzen',      name: 'Prinzen / Vencomatic site',       url: 'https://www.prinzen.com/news',         sourceClass: 'competitor-site', status: 'ok',     lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-08-14', itemsLast30d: 3,  scoredItemsLast90d: 4 },
    { id: 'src-nabel',        name: 'NABEL site (JP)',                 url: 'https://www.nabel.co.jp',              sourceClass: 'competitor-site', status: 'stale',  lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-07-08', itemsLast30d: 0,  scoredItemsLast90d: 2, language: 'Japanese' },
    { id: 'src-zenyer',       name: 'Zenyer site (CN/EN)',             url: 'https://www.zenyer.com',               sourceClass: 'competitor-site', status: 'ok',     lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-08-06', itemsLast30d: 2,  scoredItemsLast90d: 5, language: 'Chinese' },
    { id: 'src-kyowa',        name: 'Kyowa newsroom',                  url: 'https://www.kyowa-jpn.co.jp',          sourceClass: 'competitor-site', status: 'failed', lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-07-30', itemsLast30d: 1,  scoredItemsLast90d: 1, language: 'Japanese',
      failureReason: 'Page structure changed 12 Aug. Extractor returns empty. Fix queued.' },
    { id: 'src-kyowa-machinery', name: 'Kyowa Machinery (EN site)',     url: 'http://www.kyowa-machinery.co.jp/english/', sourceClass: 'competitor-site', status: 'proposed', lastRun: '2026-08-27T06:00:00Z', lastItem: null, itemsLast30d: 0, scoredItemsLast90d: 0, language: 'English' },
    { id: 'src-riva',         name: 'Riva Selegg site (IT)',           url: 'https://www.rivaselegg.com',           sourceClass: 'competitor-site', status: 'ok',     lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-07-12', itemsLast30d: 1,  scoredItemsLast90d: 2, language: 'Italian' },
    { id: 'src-wattpoultry',  name: 'WATT Poultry',                    url: 'https://www.wattagnet.com',            sourceClass: 'trade-press',     status: 'ok',     lastRun: '2026-08-19T05:30:00Z', lastItem: '2026-08-18', itemsLast30d: 14, scoredItemsLast90d: 11 },
    { id: 'src-poultryworld', name: 'Poultry World',                   url: 'https://www.poultryworld.net',         sourceClass: 'trade-press',     status: 'ok',     lastRun: '2026-08-19T05:30:00Z', lastItem: '2026-08-17', itemsLast30d: 11, scoredItemsLast90d: 8 },
    { id: 'src-patents',      name: 'Espacenet patent watch',          url: 'https://worldwide.espacenet.com',      sourceClass: 'patents',         status: 'ok',     lastRun: '2026-08-18T22:00:00Z', lastItem: '2026-08-02', itemsLast30d: 2,  scoredItemsLast90d: 3 },
    { id: 'src-viv',          name: 'Event exhibitor lists',           url: 'https://www.vivasia.nl',               sourceClass: 'events',          status: 'ok',     lastRun: '2026-08-19T04:00:00Z', lastItem: '2026-08-17', itemsLast30d: 5,  scoredItemsLast90d: 7 },
    { id: 'src-linkedin',     name: 'LinkedIn company pages',          url: 'https://www.linkedin.com',             sourceClass: 'social',          status: 'stale',  lastRun: '2026-08-16T06:00:00Z', lastItem: '2026-08-05', itemsLast30d: 4,  scoredItemsLast90d: 5,
      failureReason: 'Public pages only, rate-limited since 16 Aug. Coverage degraded, not zero.' },
    { id: 'src-jobs',         name: 'Job postings sweep',              url: 'https://www.vencomaticgroup.com/careers', sourceClass: 'jobs',         status: 'ok',     lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-08-11', itemsLast30d: 3,  scoredItemsLast90d: 2 },
    { id: 'src-sanovo-jobs',  name: 'Sanovo careers site',             url: 'https://www.sanovogroup.com/careers',  sourceClass: 'jobs',            status: 'ok',     lastRun: '2026-08-27T06:00:00Z', lastItem: '2026-08-11', itemsLast30d: 1,  scoredItemsLast90d: 1 },
    { id: 'src-moba-events',  name: 'Moba events page (context seed)', url: 'https://www.moba.net/events',          sourceClass: 'events',          status: 'ok',     lastRun: '2026-08-19T06:00:00Z', lastItem: '2026-08-12', itemsLast30d: 2,  scoredItemsLast90d: 1 },
    { id: 'src-wep',          name: 'World egg association bulletins', url: 'https://www.internationalegg.com',     sourceClass: 'association',     status: 'ok',     lastRun: '2026-08-19T05:00:00Z', lastItem: '2026-08-10', itemsLast30d: 2,  scoredItemsLast90d: 1 },
  ],

  // ── Approval queue ──────────────────────────────────────────────────────────
  proposals: [
    {
      id: 'p-01', kind: 'source', title: 'Add source: Vietnam Poultry Journal',
      rationale: 'Cited twice in Ba Huan coverage. Vietnamese-language trade portal with processing-sector news the current list misses.',
      proposedBy: 'curator', proposedOn: '2026-08-15', state: 'pending',
      sourceUrl: 'https://nhachannuoi.vn',
    },
    {
      id: 'p-02', kind: 'entity', title: 'Track new entity: Huanong Machinery',
      rationale: 'Appeared in three separate contexts in 60 days: CILE exhibitor list, a Poultry World mention, and an Indonesian tender document.',
      proposedBy: 'curator', proposedOn: '2026-08-14', state: 'pending',
      sourceUrl: 'https://www.poultryworld.net/huanong-mention',
    },
    {
      id: 'p-03', kind: 'axis', title: 'Add comparison axis: Labour automation',
      rationale: 'Prinzen robotics, NABEL palletising partnership and Zenyer wording all claim labour reduction. Current axes cannot hold these claims.',
      proposedBy: 'positioning', proposedOn: '2026-08-12', state: 'pending',
    },
    {
      id: 'p-04', kind: 'contribution', title: 'Forwarded email: Sanovo rep hired in Colombia',
      rationale: 'Forward from field sales ahead of Fenavi. Enters as credibility 1 until corroborated.',
      proposedBy: 'human', proposedOn: '2026-08-16', state: 'pending',
      contributor: 'Field sales, Americas', channel: 'email',
      why: 'Heard at a customer visit that Sanovo hired a dedicated rep for Colombia before Fenavi.',
    },
    {
      id: 'p-05', kind: 'source', title: 'Retire source: regional blog "Egg Industry Insider"',
      rationale: 'Zero scored items in 90 days. Retirement keeps the sweep budget on productive sources.',
      proposedBy: 'curator', proposedOn: '2026-08-10', state: 'accepted',
    },
    {
      id: 'p-06', kind: 'entity', title: 'Track new entity: distributor "OvoTrade BV"',
      rationale: 'Single mention in one social post.',
      proposedBy: 'curator', proposedOn: '2026-08-08', state: 'rejected',
    },
  ],

  // ── Open question queue ─────────────────────────────────────────────────────
  questions: [
    {
      id: 'q-01', question: 'Has Sanovo actually shipped the Ba Huan line, or only announced it?',
      askedBy: 'Chief Analyst', askedOn: '2026-04-06', attempts: 11, lastAttempt: '2026-08-18', state: 'open',
    },
    {
      id: 'q-02', question: 'Is the Zenyer grader CE-certified for EU sale?',
      askedBy: 'PM Grading', askedOn: '2026-06-12', attempts: 6, lastAttempt: '2026-08-17', state: 'open',
    },
    {
      id: 'q-03', question: 'Did NABEL exhibit at VIV MEA 2025?',
      askedBy: 'Mark de Kock', askedOn: '2026-08-06', attempts: 2, lastAttempt: '2026-08-09', state: 'resolved',
      resolution: 'No. Distributor presence only, confirmed against the exhibitor archive on 9 Aug.',
    },
  ],

  // ── Context corpus ──────────────────────────────────────────────────────────
  context: [
    { id: 'ctx-01', name: 'Messaging house and claim set',      owner: 'Product marketing', loadedOn: '2026-08-05', reviewBy: '2026-08-15',
      note: 'Draft version loaded. Review date passed: claims tracker rows are provisional until the house is final.' },
    { id: 'ctx-02', name: 'Four customer challenges',           owner: 'Product marketing', loadedOn: '2026-08-05', reviewBy: '2026-11-01' },
    { id: 'ctx-03', name: 'Moba product capability facts',      owner: 'Product management', loadedOn: '2026-08-07', reviewBy: '2026-11-01' },
    { id: 'ctx-04', name: 'Strategic account list',             owner: 'Sales operations',  loadedOn: '2026-08-07', reviewBy: '2026-10-01',
      note: 'Drives proximity scoring. Confidential: analyst view only.' },
    { id: 'ctx-05', name: 'Moba event calendar',                owner: 'Events team',       loadedOn: '2026-08-05', reviewBy: '2026-09-15' },
    { id: 'ctx-06', name: 'Asia landscape research (complete)', owner: 'Chief Analyst',     loadedOn: '2026-08-05', reviewBy: '2027-02-01',
      note: 'Timeline baseline for Asia. Europe and Americas load as those phases complete.' },
    { id: 'ctx-07', name: 'Moba published whitepapers',         owner: 'Product marketing', loadedOn: '2026-08-08', reviewBy: '2026-12-01',
      note: 'Context and public claims in one. The agent tracks these for contestation.' },
  ],

  // ── Share of voice (illustrative, mirrors the LinkedIn import shape) ────────
  social: [
    // 12-month baseline window
    { entityId: 'moba',   periodStart: '2025-08-19', periodEnd: '2026-06-18', followers: 32000, newFollowers: 3300, engagements: 9400,  posts: 126 },
    { entityId: 'sanovo', periodStart: '2025-08-19', periodEnd: '2026-06-18', followers: 17600, newFollowers: 2600, engagements: 8800,  posts: 148 },
    { entityId: 'nabel',  periodStart: '2025-08-19', periodEnd: '2026-06-18', followers: 4100,  newFollowers: 500,  engagements: 2100,  posts: 60 },
    { entityId: 'zenyer', periodStart: '2025-08-19', periodEnd: '2026-06-18', followers: 2900,  newFollowers: 700,  engagements: 1500,  posts: 52 },
    // two monthly points
    { entityId: 'moba',   periodStart: '2026-06-19', periodEnd: '2026-07-18', followers: 33000, newFollowers: 310, engagements: 640, posts: 10 },
    { entityId: 'sanovo', periodStart: '2026-06-19', periodEnd: '2026-07-18', followers: 17900, newFollowers: 180, engagements: 690, posts: 14 },
    { entityId: 'nabel',  periodStart: '2026-06-19', periodEnd: '2026-07-18', followers: 4200,  newFollowers: 60,  engagements: 240, posts: 6 },
    { entityId: 'zenyer', periodStart: '2026-06-19', periodEnd: '2026-07-18', followers: 3000,  newFollowers: 90,  engagements: 170, posts: 5 },
    { entityId: 'moba',   periodStart: '2026-07-19', periodEnd: '2026-08-18', followers: 33400, newFollowers: 320, engagements: 380, posts: 8 },
    { entityId: 'sanovo', periodStart: '2026-07-19', periodEnd: '2026-08-18', followers: 18100, newFollowers: 150, engagements: 710, posts: 17 },
    { entityId: 'nabel',  periodStart: '2026-07-19', periodEnd: '2026-08-18', followers: 4260,  newFollowers: 70,  engagements: 310, posts: 7 },
    { entityId: 'zenyer', periodStart: '2026-07-19', periodEnd: '2026-08-18', followers: 3080,  newFollowers: 110, engagements: 220, posts: 6 },
  ],

  // ── Weekly brief (illustrative: agent-drafted, analyst-approved) ────────────
  brief: {
    weekStart: '2026-08-17',
    temperature: 'elevated',
    headline: 'Sanovo holds its processing momentum into a third Southeast Asia win while NABEL puts a number on detection. Both touch contested claims; neither is answered in market yet.',
    whatHappened: 'Four competitor items this week: a third Sanovo processing win in Thailand, a NABEL session slot in Riyadh, a Prinzen connected-packer teaser for SPACE, and a Diamond installed-base article classified under Moba.',
    keyDevelopment: 'Sanovo explicitly frames its Thailand win as regional momentum, the third SEA processing announcement this quarter.',
    whyItMatters: 'The processing claim is the most contested position in the messaging house, and the pattern is now a quarter-long streak at strategic-account level.',
    mobaAdvantage: 'iMoba multi-site benchmarking and the integrated grading-to-processing story remain unmatched in the week\'s material.',
    marketingResponse: 'Hold processing claims out of Vietnam material until the Ba Huan scope is verified; brief the SPACE team to capture Prinzen wording.',
    salesResponse: 'Update the Sanovo battlecard processing section with the three SEA wins and the stated delivery timelines.',
    watchNext: 'Prinzen connected-packer reveal at SPACE (15 Sep) and any Ba Huan delivery confirmation.',
    changes: [
      { entity: 'Sanovo', change: 'Third SEA processing win this quarter, framed as regional momentum.' },
      { entity: 'NABEL', change: 'First Saudi Agriculture appearance, speaking on AI in egg quality.' },
      { entity: 'Prinzen (part of Vencomatic)', change: 'Connected packer teased for SPACE 2026.' },
    ],
    approvedBy: 'Chief Analyst',
    approvedAt: '2026-08-17T08:00:00Z',
  },

  // ── Brand & positioning paper (illustrative sample edition) ─────────────────
  paper: {
    edition: '2026-Q3',
    subjects: ['moba', 'sanovo', 'nabel'],
    generatedAt: '2026-08-01T07:30:00Z',
    profiles: [
      {
        entityId: 'moba',
        snapshot: [
          { text: 'Headquarters in Barneveld, the Netherlands; grading, packing and processing equipment.', sourceUrl: 'https://www.moba.net' },
          { text: 'Global sales and service organisation with regional subsidiaries.', sourceUrl: 'https://www.moba.net' },
        ],
        tagline: 'Sample: the complete egg journey, one partner',
        positioningSummary: 'Presents itself as the integration leader: grading, packing and processing as one connected line with iMoba data on top. The copy leads with scale, uptime and the installed base.',
        claims: [
          { text: 'Only supplier covering the full grading-to-processing chain with one control layer.', sourceUrl: 'https://www.moba.net' },
          { text: 'iMoba benchmarks performance across sites.', sourceUrl: 'https://www.moba.net' },
        ],
        themes: {
          integration: { score: 3, evidence: [{ text: 'One partner for the complete egg journey.', sourceUrl: 'https://www.moba.net' }] },
          foodsafety: { score: 3, evidence: [{ text: 'Grading accuracy and food safety front and centre.', sourceUrl: 'https://www.moba.net' }] },
          capacity: { score: 3, evidence: [{ text: 'Flagship capacity figures lead the product pages.', sourceUrl: 'https://www.moba.net' }] },
          digital: { score: 3, evidence: [{ text: 'iMoba platform carries the digital story.', sourceUrl: 'https://www.moba.net' }] },
          service: { score: 2, evidence: [{ text: 'Global service network referenced across pages.', sourceUrl: 'https://www.moba.net' }] },
          sustainability: { score: 2, evidence: [{ text: 'Energy per egg appears in newer copy.', sourceUrl: 'https://www.moba.net' }] },
          welfare: { score: 1, evidence: [] },
          cost: { score: 1, evidence: [] },
        },
        audience: [{ text: 'Large graders and packers, multi-site operations, integrators.', sourceUrl: 'https://www.moba.net' }],
        proofPoints: [{ text: 'Installed base and named flagship lines.', sourceUrl: 'https://www.moba.net' }],
        channelBehaviour: 'LinkedIn, latest imported period: 13 posts, 278 engagements across mapped pages.',
      },
      {
        entityId: 'sanovo',
        snapshot: [
          { text: 'Headquarters in Odense, Denmark; egg handling and egg processing technology.', sourceUrl: 'https://www.sanovogroup.com' },
        ],
        tagline: 'Sample: from egg to opportunity',
        positioningSummary: 'Leads with processing: breaking, separating and pasteurising presented as one integrated line. Handling (Staalkat heritage) supports the story; regional momentum wins carry the news feed.',
        claims: [
          { text: 'Integrated processing line with a single control layer.', sourceUrl: 'https://www.sanovogroup.com' },
          { text: 'Regional proximity through hubs and local service.', sourceUrl: 'https://www.sanovogroup.com' },
        ],
        themes: {
          integration: { score: 3, evidence: [{ text: 'One line from breaking to pasteurising.', sourceUrl: 'https://www.sanovogroup.com' }] },
          foodsafety: { score: 3, evidence: [{ text: 'Pasteurisation and hygiene lead the processing pages.', sourceUrl: 'https://www.sanovogroup.com' }] },
          capacity: { score: 2, evidence: [{ text: 'Throughput quoted per line, not as headline.', sourceUrl: 'https://www.sanovogroup.com' }] },
          digital: { score: 2, evidence: [{ text: 'New control layer marketed with the line.', sourceUrl: 'https://www.sanovogroup.com' }] },
          service: { score: 2, evidence: [{ text: 'Bangkok hub framed around response time.', sourceUrl: 'https://www.sanovogroup.com' }] },
          sustainability: { score: 2, evidence: [{ text: 'Water and energy reduction per processed egg.', sourceUrl: 'https://www.sanovogroup.com' }] },
          welfare: { score: 0, evidence: [] },
          cost: { score: 2, evidence: [{ text: 'Yield and total cost of ownership recur.', sourceUrl: 'https://www.sanovogroup.com' }] },
        },
        audience: [{ text: 'Egg processors first, packers second; strong emphasis on Southeast Asia.', sourceUrl: 'https://www.sanovogroup.com' }],
        proofPoints: [{ text: 'Three announced SEA processing wins this quarter.', sourceUrl: 'https://www.sanovogroup.com' }],
        channelBehaviour: 'LinkedIn, latest imported period: 8 posts, 323 engagements across mapped pages.',
      },
      {
        entityId: 'nabel',
        snapshot: [
          { text: 'Headquarters in Kyoto, Japan; egg grading and packing systems.', sourceUrl: 'https://www.nabel.co.jp/en/' },
        ],
        tagline: 'Sample: precision in every egg',
        positioningSummary: 'Positions on detection precision: crack and dirt detection accuracy with published numbers, AI inspection as the frontier story. Domestic strength in Japan, expanding presence in Asia and the Middle East.',
        claims: [
          { text: '99.5% crack-detection accuracy claimed for the AI inspection module.', sourceUrl: 'https://www.nabel.co.jp/en/' },
          { text: 'Compact footprint for mid-capacity plants.', sourceUrl: 'https://www.nabel.co.jp/en/' },
        ],
        themes: {
          integration: { score: 1, evidence: [] },
          foodsafety: { score: 3, evidence: [{ text: 'Detection accuracy is the core promise.', sourceUrl: 'https://www.nabel.co.jp/en/' }] },
          capacity: { score: 2, evidence: [{ text: 'Mid-capacity positioning, 60k eggs per hour.', sourceUrl: 'https://www.nabel.co.jp/en/' }] },
          digital: { score: 2, evidence: [{ text: 'AI inspection carries the technology story.', sourceUrl: 'https://www.nabel.co.jp/en/' }] },
          service: { score: 1, evidence: [] },
          sustainability: { score: 1, evidence: [] },
          welfare: { score: 0, evidence: [] },
          cost: { score: 2, evidence: [{ text: 'Footprint and energy use as buying arguments.', sourceUrl: 'https://www.nabel.co.jp/en/' }] },
        },
        audience: [{ text: 'Mid-capacity plants; Japan first, Asia Pacific and Middle East growth.', sourceUrl: 'https://www.nabel.co.jp/en/' }],
        proofPoints: [{ text: 'Published detection-accuracy figures; Riyadh conference session slot.', sourceUrl: 'https://www.nabel.co.jp/en/' }],
        channelBehaviour: 'No share-of-voice data imported for this company yet.',
      },
    ],
    map: {
      placements: [
        { entityId: 'moba', x: 84, y: 62, rationale: 'Full-chain integration claim with a mature digital layer; innovation framed on proven scale.' },
        { entityId: 'sanovo', x: 72, y: 54, rationale: 'Integrated within processing; new control layer moves the tech story forward.' },
        { entityId: 'nabel', x: 28, y: 74, rationale: 'Machine-level focus with the most aggressive frontier claim: published AI detection numbers.' },
      ],
    },
    collisions: [
      { claim: 'One integrated line, one control layer', entityIds: ['moba', 'sanovo'], note: 'Moba claims it across the whole chain, Sanovo within processing. Same words, different scope.' },
      { claim: 'Detection accuracy leadership', entityIds: ['moba', 'nabel'], note: 'NABEL publishes a number; Moba claims it without one. A number beats an adjective in a bake-off.' },
    ],
    changes: [],
    implications: 'Sample edition. Sanovo’s control-layer language now overlaps the keten claim inside processing: sharpen the scope difference in the messaging house. NABEL’s published accuracy number is the kind of claim that wins bake-offs; consider publishing a verified figure or reframing the comparison. The welfare theme is unclaimed by everyone: whitespace if the market starts asking.',
    approvedBy: 'Chief Analyst',
    approvedAt: '2026-08-02T09:00:00Z',
  },

  // ── Analyst headline (immutable to the agent) ───────────────────────────────
  headlineOverride: {
    text: 'Sanovo has announced three processing-line wins in Southeast Asia this quarter against one in the prior quarter, including one at a Moba strategic account. Our processing claim is now the most contested position in the messaging house.',
    author: 'Chief Analyst',
    writtenOn: '2026-08-14',
  },
}
