// FILE: src/products/cloud_readiness/questions.ts
// ─── Cloud Readiness Assessment — 30 questions across 6 dimensions ────────────
//
// 5 questions per dimension. First question in each dimension is lite=true
// (6 lite questions total for a quick 6-question scan).
//
// Dimension keys:
//   cloud_strategy            Cloud Strategy & Business Alignment  (weight 0.22)
//   cloud_adoption            Current Cloud Adoption               (weight 0.22)
//   infrastructure_arch       Infrastructure & Architecture        (weight 0.16)
//   devops_automation         DevOps & Automation                  (weight 0.15)
//   security_compliance       Security & Compliance                (weight 0.15)
//   finops_cost               FinOps & Cost Management             (weight 0.10)

import type { Question } from '@/data/questions'

export const CLOUD_QUESTIONS: Question[] = [

  // ── CLOUD STRATEGY & BUSINESS ALIGNMENT ─────────────────────────────────────
  {
    code: 'CS1',
    dimension: 'cloud_strategy' as Question['dimension'],
    text: 'How central is cloud technology to your organisation\'s current strategy?',
    type: 'likert',
    lite: true,
    scored: true,
    options: [
      { value: 1, label: 'Not on the agenda' },
      { value: 2, label: 'Occasionally discussed but no concrete plans' },
      { value: 3, label: 'Part of our strategy in some areas' },
      { value: 4, label: 'Actively integrated into strategic planning' },
      { value: 5, label: 'Central to how we operate and compete' },
    ],
  },
  {
    code: 'CS2',
    dimension: 'cloud_strategy' as Question['dimension'],
    text: 'How would you describe leadership\'s commitment to cloud transformation?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No visible interest from leadership' },
      { value: 2, label: 'Awareness but no dedicated sponsorship' },
      { value: 3, label: 'One or two senior sponsors actively engaged' },
      { value: 4, label: 'Broad leadership buy-in with resources allocated' },
      { value: 5, label: 'Cloud is a board-level priority with dedicated investment' },
    ],
  },
  {
    code: 'CS3',
    dimension: 'cloud_strategy' as Question['dimension'],
    text: 'Does your organisation have a documented cloud roadmap?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No roadmap exists' },
      { value: 2, label: 'Informally discussed but not documented' },
      { value: 3, label: 'A roadmap exists but is not actively maintained' },
      { value: 4, label: 'A clear roadmap with milestones and owners' },
      { value: 5, label: 'A living roadmap regularly reviewed and updated by leadership' },
    ],
  },
  {
    code: 'CS4',
    dimension: 'cloud_strategy' as Question['dimension'],
    text: 'How well do business stakeholders understand the value and goals of your cloud investment?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Cloud is seen as an IT topic — not a business concern' },
      { value: 2, label: 'Some awareness but no shared objectives' },
      { value: 3, label: 'Key stakeholders are aligned on high-level goals' },
      { value: 4, label: 'Business and IT share clear, measurable cloud objectives' },
      { value: 5, label: 'Cloud outcomes are tied directly to business KPIs' },
    ],
  },
  {
    code: 'CS5',
    dimension: 'cloud_strategy' as Question['dimension'],
    text: 'How is cloud investment budgeted in your organisation?',
    type: 'weighted_mc',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No dedicated cloud budget — costs absorbed ad hoc' },
      { value: 2, label: 'Budget exists but is reactive and unplanned' },
      { value: 3, label: 'Annual budget approved but not optimised' },
      { value: 4, label: 'Planned budget with quarterly reviews' },
      { value: 5, label: 'Multi-year investment plan with ROI tracking' },
    ],
  },

  // ── CURRENT CLOUD ADOPTION ───────────────────────────────────────────────────
  {
    code: 'CA1',
    dimension: 'cloud_adoption' as Question['dimension'],
    text: 'What percentage of your workloads currently run in the cloud?',
    type: 'weighted_mc',
    lite: true,
    scored: true,
    options: [
      { value: 1, label: 'Less than 10% — we are mostly on-premises' },
      { value: 2, label: '10–30% — early movers, mostly non-critical workloads' },
      { value: 3, label: '30–60% — significant cloud presence' },
      { value: 4, label: '60–80% — cloud-first with some legacy remaining' },
      { value: 5, label: 'More than 80% — cloud-native or cloud-majority' },
    ],
  },
  {
    code: 'CA2',
    dimension: 'cloud_adoption' as Question['dimension'],
    text: 'How long has your organisation been actively using cloud infrastructure?',
    type: 'weighted_mc',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'We haven\'t started yet' },
      { value: 2, label: 'Less than 1 year — just getting started' },
      { value: 3, label: '1–3 years — building our foundation' },
      { value: 4, label: '3–5 years — established cloud presence' },
      { value: 5, label: 'More than 5 years — cloud is our default' },
    ],
  },
  {
    code: 'CA3',
    dimension: 'cloud_adoption' as Question['dimension'],
    text: 'How would you describe the maturity of your applications in the cloud?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Lift-and-shift only — applications unchanged from on-premises' },
      { value: 2, label: 'Mostly re-hosted, some re-platforming started' },
      { value: 3, label: 'Mix of re-hosted and re-architected workloads' },
      { value: 4, label: 'Most applications re-architected for cloud efficiency' },
      { value: 5, label: 'Cloud-native: microservices, serverless, and managed services throughout' },
    ],
  },
  {
    code: 'CA4',
    dimension: 'cloud_adoption' as Question['dimension'],
    text: 'How broadly is cloud used across your organisation\'s business units?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Only one team or department uses cloud' },
      { value: 2, label: 'A few isolated teams — no coordination' },
      { value: 3, label: 'Multiple teams, with some shared standards' },
      { value: 4, label: 'Most business units on cloud with a shared platform' },
      { value: 5, label: 'Organisation-wide adoption with a central cloud platform team' },
    ],
  },
  {
    code: 'CA5',
    dimension: 'cloud_adoption' as Question['dimension'],
    text: 'How does your organisation manage cloud provider relationships?',
    type: 'weighted_mc',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No formal relationship — we buy directly online' },
      { value: 2, label: 'We have an account manager but rarely engage' },
      { value: 3, label: 'Regular contact, occasional joint initiatives' },
      { value: 4, label: 'Strategic partnership with shared roadmap discussions' },
      { value: 5, label: 'Partner programme membership with dedicated support and credits' },
    ],
  },

  // ── INFRASTRUCTURE & ARCHITECTURE ───────────────────────────────────────────
  {
    code: 'IA1',
    dimension: 'infrastructure_arch' as Question['dimension'],
    text: 'How mature is your use of Infrastructure as Code (IaC)?',
    type: 'likert',
    lite: true,
    scored: true,
    options: [
      { value: 1, label: 'We manage infrastructure manually through the console' },
      { value: 2, label: 'Some scripting, but no formal IaC tooling' },
      { value: 3, label: 'IaC adopted for some environments (e.g. Terraform, CDK)' },
      { value: 4, label: 'Most infrastructure defined as code and version-controlled' },
      { value: 5, label: 'Full IaC with automated provisioning and policy enforcement' },
    ],
  },
  {
    code: 'IA2',
    dimension: 'infrastructure_arch' as Question['dimension'],
    text: 'How would you describe your container and Kubernetes adoption?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No containers in use' },
      { value: 2, label: 'Docker used in development, not production' },
      { value: 3, label: 'Containers in production, Kubernetes being evaluated' },
      { value: 4, label: 'Kubernetes running in production for some workloads' },
      { value: 5, label: 'Kubernetes is our primary deployment platform across all workloads' },
    ],
  },
  {
    code: 'IA3',
    dimension: 'infrastructure_arch' as Question['dimension'],
    text: 'What is your organisation\'s cloud architecture approach?',
    type: 'weighted_mc',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Single cloud — one provider, minimal cloud-native services' },
      { value: 2, label: 'Single cloud — using managed services and cloud-native features' },
      { value: 3, label: 'Hybrid — cloud plus on-premises, integrated' },
      { value: 4, label: 'Multi-cloud — two or more providers, deliberately chosen' },
      { value: 5, label: 'Multi-cloud — abstracted platform, workload portability by design' },
    ],
  },
  {
    code: 'IA4',
    dimension: 'infrastructure_arch' as Question['dimension'],
    text: 'How are your disaster recovery and business continuity capabilities set up?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No formal DR plan — we rely on manual backups' },
      { value: 2, label: 'Backups exist but recovery has not been tested' },
      { value: 3, label: 'DR plan documented and tested annually' },
      { value: 4, label: 'Automated failover for critical workloads, tested regularly' },
      { value: 5, label: 'Multi-region active-active architecture with RTO/RPO SLAs met' },
    ],
  },
  {
    code: 'IA5',
    dimension: 'infrastructure_arch' as Question['dimension'],
    text: 'How well does your architecture support scalability and elasticity?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Fixed-size infrastructure — scaling requires manual intervention' },
      { value: 2, label: 'Some autoscaling configured for specific services' },
      { value: 3, label: 'Most services scale automatically based on demand' },
      { value: 4, label: 'Elastic infrastructure with cost and performance balanced automatically' },
      { value: 5, label: 'Fully serverless and event-driven where appropriate — zero idle cost' },
    ],
  },

  // ── DEVOPS & AUTOMATION ──────────────────────────────────────────────────────
  {
    code: 'DA1',
    dimension: 'devops_automation' as Question['dimension'],
    text: 'How mature are your CI/CD pipelines?',
    type: 'likert',
    lite: true,
    scored: true,
    options: [
      { value: 1, label: 'No CI/CD — deployments are manual' },
      { value: 2, label: 'Basic CI in place, deployments still partly manual' },
      { value: 3, label: 'CI/CD pipelines for most services with automated testing' },
      { value: 4, label: 'Full CI/CD with automated security scanning and quality gates' },
      { value: 5, label: 'Platform engineering team — golden paths and self-service deployment' },
    ],
  },
  {
    code: 'DA2',
    dimension: 'devops_automation' as Question['dimension'],
    text: 'How frequently does your team deploy to production?',
    type: 'frequency',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Less than once per month — large infrequent releases' },
      { value: 2, label: 'Monthly — planned release cycles' },
      { value: 3, label: 'Weekly — regular sprint-based deployments' },
      { value: 4, label: 'Daily or multiple times per week' },
      { value: 5, label: 'Multiple times per day — on-demand deployment' },
    ],
  },
  {
    code: 'DA3',
    dimension: 'devops_automation' as Question['dimension'],
    text: 'How automated are your cloud operations (patching, scaling, incident response)?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Mostly manual — operations rely on individual knowledge' },
      { value: 2, label: 'Some runbooks, automation is ad hoc' },
      { value: 3, label: 'Routine tasks automated, incidents still require manual response' },
      { value: 4, label: 'Most operations automated, alerts trigger automated remediation' },
      { value: 5, label: 'AIOps — predictive automation, self-healing infrastructure' },
    ],
  },
  {
    code: 'DA4',
    dimension: 'devops_automation' as Question['dimension'],
    text: 'How would you describe your observability capabilities (logging, monitoring, tracing)?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Basic uptime monitoring only' },
      { value: 2, label: 'Centralised logging but limited alerting' },
      { value: 3, label: 'Metrics and alerts across most services' },
      { value: 4, label: 'Full-stack observability: logs, metrics, traces, dashboards' },
      { value: 5, label: 'SLO-driven observability with anomaly detection and capacity forecasting' },
    ],
  },
  {
    code: 'DA5',
    dimension: 'devops_automation' as Question['dimension'],
    text: 'How empowered are developers to provision and manage their own cloud resources?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'All cloud resources managed centrally by ops — developers have no access' },
      { value: 2, label: 'Developers can request resources, fulfilled by ops within days' },
      { value: 3, label: 'Self-service for common resources, some guardrails in place' },
      { value: 4, label: 'Developer portal with approved catalogue — provisioning in minutes' },
      { value: 5, label: 'Full internal developer platform — environments on demand, policy as code' },
    ],
  },

  // ── SECURITY & COMPLIANCE ────────────────────────────────────────────────────
  {
    code: 'SC1',
    dimension: 'security_compliance' as Question['dimension'],
    text: 'How mature are your cloud security policies and controls?',
    type: 'likert',
    lite: true,
    scored: true,
    options: [
      { value: 1, label: 'No formal cloud security policy exists' },
      { value: 2, label: 'Basic policies exist but are not consistently enforced' },
      { value: 3, label: 'Documented security standards enforced for most workloads' },
      { value: 4, label: 'Automated policy enforcement with regular audits' },
      { value: 5, label: 'Security as code — guardrails baked into the delivery pipeline' },
    ],
  },
  {
    code: 'SC2',
    dimension: 'security_compliance' as Question['dimension'],
    text: 'How is Identity and Access Management (IAM) handled in your cloud environment?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Shared accounts or root credentials in use' },
      { value: 2, label: 'Individual accounts, limited role separation' },
      { value: 3, label: 'Role-based access with least-privilege principles applied' },
      { value: 4, label: 'Centralised IAM with SSO and MFA enforced' },
      { value: 5, label: 'Zero-trust architecture with just-in-time access and continuous verification' },
    ],
  },
  {
    code: 'SC3',
    dimension: 'security_compliance' as Question['dimension'],
    text: 'How is sensitive data classified and protected in the cloud?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No data classification — all data treated equally' },
      { value: 2, label: 'Informal classification, limited technical controls' },
      { value: 3, label: 'Data classification policy with encryption at rest and in transit' },
      { value: 4, label: 'Automated data discovery, classification, and DLP controls' },
      { value: 5, label: 'Comprehensive data governance with audit trails and residency controls' },
    ],
  },
  {
    code: 'SC4',
    dimension: 'security_compliance' as Question['dimension'],
    text: 'How does your organisation manage compliance requirements in the cloud (e.g. ISO 27001, NIS2, GDPR)?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Compliance is not actively managed in our cloud environment' },
      { value: 2, label: 'Manual checks, mostly reactive to audit findings' },
      { value: 3, label: 'Key compliance controls documented and reviewed periodically' },
      { value: 4, label: 'Automated compliance monitoring with continuous assessment' },
      { value: 5, label: 'Compliance as code — controls automated, evidence generated continuously' },
    ],
  },
  {
    code: 'SC5',
    dimension: 'security_compliance' as Question['dimension'],
    text: 'How prepared is your organisation to detect and respond to a cloud security incident?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No incident response plan for cloud environments' },
      { value: 2, label: 'Generic IR plan exists but is not cloud-specific' },
      { value: 3, label: 'Cloud-specific IR playbooks with defined roles and escalation paths' },
      { value: 4, label: 'Regular incident response exercises including cloud scenarios' },
      { value: 5, label: 'Automated detection, containment, and forensics — MTTR measured and improving' },
    ],
  },

  // ── FINOPS & COST MANAGEMENT ─────────────────────────────────────────────────
  {
    code: 'FC1',
    dimension: 'finops_cost' as Question['dimension'],
    text: 'How visible are your cloud costs across teams and workloads?',
    type: 'likert',
    lite: true,
    scored: true,
    options: [
      { value: 1, label: 'We receive a single monthly bill with no breakdown' },
      { value: 2, label: 'Some cost visibility but tagging is inconsistent' },
      { value: 3, label: 'Costs visible per service, some team-level attribution' },
      { value: 4, label: 'Full cost attribution by team, product, and environment' },
      { value: 5, label: 'Real-time cost dashboards with anomaly alerts and chargeback' },
    ],
  },
  {
    code: 'FC2',
    dimension: 'finops_cost' as Question['dimension'],
    text: 'How actively does your organisation optimise cloud spend?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No optimisation — we pay on-demand for everything' },
      { value: 2, label: 'Occasional reviews, some reserved instances purchased' },
      { value: 3, label: 'Regular rightsizing and commitment discount reviews' },
      { value: 4, label: 'Automated rightsizing recommendations actively implemented' },
      { value: 5, label: 'FinOps practice in place — continuous optimisation as a discipline' },
    ],
  },
  {
    code: 'FC3',
    dimension: 'finops_cost' as Question['dimension'],
    text: 'How accurate is your cloud cost forecasting?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'We don\'t forecast — costs are reviewed after the fact' },
      { value: 2, label: 'Annual estimates, rarely revised' },
      { value: 3, label: 'Quarterly forecasts with moderate accuracy' },
      { value: 4, label: 'Monthly rolling forecasts within 15% variance' },
      { value: 5, label: 'Continuous forecasting with predictive models — within 5% variance' },
    ],
  },
  {
    code: 'FC4',
    dimension: 'finops_cost' as Question['dimension'],
    text: 'How consistently are cloud resources tagged for cost allocation?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'No tagging strategy — most resources are untagged' },
      { value: 2, label: 'Some tags applied manually, no enforcement' },
      { value: 3, label: 'Tagging policy exists, applied to most new resources' },
      { value: 4, label: 'Mandatory tagging enforced via policy — high coverage' },
      { value: 5, label: 'Full tagging with automated remediation for non-compliant resources' },
    ],
  },
  {
    code: 'FC5',
    dimension: 'finops_cost' as Question['dimension'],
    text: 'How accountable are individual teams for their cloud spend?',
    type: 'likert',
    lite: false,
    scored: true,
    options: [
      { value: 1, label: 'Cloud costs are a central IT concern — teams have no visibility' },
      { value: 2, label: 'Teams are occasionally informed of their spend' },
      { value: 3, label: 'Teams have budget targets and receive monthly cost reports' },
      { value: 4, label: 'Teams own their cloud budget with regular review cadence' },
      { value: 5, label: 'Full financial ownership — teams optimise proactively and are measured on cloud efficiency' },
    ],
  },
]
