'use client'

// ─── Moba Signal — competitive intelligence dashboard ────────────────────────
// One surface, ten tiers, ordered by the ruthless-ranking principle: the value
// is not the volume of data, it is what floats to the top. Status bar sticks,
// headline states the situation, the timeline is the spine.

import { useMemo, useState } from 'react'
import type { Signal, SignalDataset } from '@/products/moba_signal/types'
import { band, daysBetween, headline, laneEntityId, sortForFeed, statusMetrics, fmtDate } from '@/products/moba_signal/selectors'
import { SignalDetail } from './SignalDetail'
import { Timeline } from './Timeline'
import { Feed } from './Feed'
import { Claims } from './Claims'
import { HeadToHead } from './HeadToHead'
import { Events } from './Events'
import { Wins } from './Wins'
import { SourceHealth } from './SourceHealth'
import { Queue } from './Queue'

const TONE_CLS = {
  alert: 'text-red-600',
  watch: 'text-amber-600',
  ok:    'text-gray-800',
} as const

function Section({ id, title, sub, children }: {
  id: string
  title: string
  sub?: string
  children: React.ReactNode
}) {
  return (
    <section id={id} className="scroll-mt-24">
      <div className="mb-4">
        <h2 className="text-base font-bold text-gray-900">{title}</h2>
        {sub && <p className="text-xs text-gray-400 mt-0.5">{sub}</p>}
      </div>
      {children}
    </section>
  )
}

const NAV = [
  { id: 'timeline',  label: 'Timeline' },
  { id: 'h2h',       label: 'Head to head' },
  { id: 'claims',    label: 'Claims' },
  { id: 'wins',      label: 'Wins' },
  { id: 'events',    label: 'Events' },
  { id: 'feed',      label: 'Feed' },
  { id: 'queue',     label: 'Queue' },
  { id: 'sources',   label: 'Sources' },
]

export function SignalDashboard({ data }: { data: SignalDataset }) {
  const [selected, setSelected] = useState<Signal | null>(null)

  const metrics = useMemo(() => statusMetrics(data), [data])
  const head = useMemo(() => headline(data), [data])
  // Top alerts: critical competitor items from the last two quarters. Moba's own
  // moves and older criticals stay visible in the timeline and the feed.
  const criticals = useMemo(
    () => sortForFeed(data.signals.filter(s =>
      band(s) === 'critical' &&
      laneEntityId(data, s.entityId) !== 'moba' &&
      daysBetween(s.date, data.asOf) <= 180
    )),
    [data]
  )

  return (
    <main className="min-h-screen bg-gray-50">
      {/* ── Tier 1: status bar, sticky ── */}
      <div className="sticky top-0 z-40 bg-white/95 backdrop-blur border-b border-gray-200 shadow-sm">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center justify-between gap-4 mb-2">
            <div className="flex items-baseline gap-2 min-w-0">
              <span className="font-bold text-brand whitespace-nowrap">Moba Signal</span>
              <span className="text-[11px] text-gray-400 whitespace-nowrap">as of {fmtDate(data.asOf)} · prototype, sample data</span>
            </div>
            <nav className="hidden md:flex gap-3 text-xs text-gray-500">
              {NAV.map(n => (
                <a key={n.id} href={`#${n.id}`} className="hover:text-brand transition-colors">{n.label}</a>
              ))}
            </nav>
          </div>
          <div className="grid grid-cols-3 md:grid-cols-6 gap-x-4 gap-y-2">
            {metrics.map(m => (
              <div key={m.key} className="min-w-0">
                <div className={`text-lg font-bold leading-tight ${TONE_CLS[m.tone]}`}>{m.value}</div>
                <div className="text-[10px] text-gray-500 leading-tight truncate" title={m.label}>{m.label}</div>
                <div className="text-[10px] text-gray-400 leading-tight truncate" title={m.baseline}>{m.baseline}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 space-y-12">
        {/* ── Tier 2: the headline ── */}
        <section>
          <p className="text-lg sm:text-xl font-medium text-gray-900 leading-snug max-w-3xl">{head.text}</p>
          <p className="text-[11px] text-gray-400 mt-2">
            {head.author
              ? `Written by ${head.author}, ${data.headlineOverride ? fmtDate(data.headlineOverride.writtenOn) : ''}. Overrides the agent draft until the next material change.`
              : 'Auto-generated by the Editor agent. The analyst can override it.'}
          </p>

          {/* Critical items surface at the very top, per the display rules */}
          {criticals.length > 0 && (
            <div className="mt-5 space-y-2">
              {criticals.map(s => (
                <button
                  key={s.id}
                  onClick={() => setSelected(s)}
                  className="w-full text-left rounded-xl border border-red-200 bg-red-50 px-4 py-3 hover:bg-red-100/70 transition-colors"
                >
                  <span className="text-[10px] font-bold uppercase tracking-wide text-red-600">Critical · {fmtDate(s.date)}</span>
                  <span className="block text-sm font-semibold text-gray-900 mt-0.5">{s.title}</span>
                  <span className="block text-xs text-gray-600 mt-0.5">{s.summary}</span>
                  {s.annotations.length === 0 && (
                    <span className="block text-[11px] text-red-600 mt-1 font-medium">Analyst &ldquo;so what&rdquo; required within 48 hours.</span>
                  )}
                </button>
              ))}
            </div>
          )}
        </section>

        {/* ── Tier 3: timeline ── */}
        <Section id="timeline" title="Timeline" sub="24 months of movement. Moba's lane on top: when we were talking, and when they were. Click any point for the source and annotations.">
          <div className="rounded-xl border border-gray-100 bg-white p-4">
            <Timeline data={data} onSelect={setSelected} />
          </div>
        </Section>

        {/* ── Tier 4: head to head ── */}
        <Section id="h2h" title="Head to head" sub="Fixed axis set, confidence and last-verified on every cell. Proposed axes appear greyed until approved.">
          <HeadToHead data={data} />
        </Section>

        {/* ── Tier 5: claims tracker ── */}
        <Section id="claims" title="Claims and positioning" sub="Every messaging-house claim against what competitors say, in their own words.">
          <Claims data={data} />
        </Section>

        {/* ── Tier 6: wins ── */}
        <Section id="wins" title="Wins and references" sub="Publicly announced wins by region. Red flag: touches a Moba strategic account.">
          <Wins data={data} onSelect={setSelected} />
        </Section>

        {/* ── Tier 7: event radar ── */}
        <Section id="events" title="Event radar" sub="The only predictive module. Rolling 12-month calendar with the T-90 to T+30 monitoring cadence.">
          <Events data={data} />
        </Section>

        {/* ── Tier 8: technology radar (P2: designed, not built) ── */}
        <Section id="tech" title="Technology radar" sub="Adopt / trial / assess / watch, fed by patents, sessions, job postings.">
          <div className="rounded-xl border border-dashed border-gray-300 bg-white p-6 text-center">
            <p className="text-sm text-gray-500">
              Designed for, not built in v1 (P2). Deliberately slow-moving: this tier should change monthly, not daily.
            </p>
            <p className="text-xs text-gray-400 mt-1">
              Early signals already collected: Zenyer optical-detection patents, NABEL AI inspection, Prinzen connected-services hiring.
            </p>
          </div>
        </Section>

        {/* ── Tier 9: raw feed ── */}
        <Section id="feed" title="Raw feed" sub="Everything collected, ranked by impact. Noise is collapsed, not deleted.">
          <Feed data={data} onSelect={setSelected} />
        </Section>

        {/* ── Curator queue and contributions ── */}
        <Section id="queue" title="Curator queue" sub="Agent proposals, human contributions and open questions. Nothing publishes without approval.">
          <Queue data={data} />
        </Section>

        {/* ── Tier 10: method and source health ── */}
        <Section id="sources" title="Method and source health" sub="Honesty about gaps is what makes the rest trustworthy.">
          <SourceHealth data={data} />
        </Section>

        <footer className="pt-4 pb-8 border-t border-gray-200 text-[11px] text-gray-400 space-y-1">
          <p>Internal prototype for Moba marketing and innovation. All items above are illustrative sample data, not collected intelligence.</p>
          <p>Impact model: proximity + materiality + credibility. Critical 8-9 · Notable 5-7 · Context 3-4 · Noise below 3. An item can never be Critical on credibility 1.</p>
        </footer>
      </div>

      {selected && <SignalDetail signal={selected} data={data} onClose={() => setSelected(null)} />}
    </main>
  )
}
